# Offense count: 5
Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'lib/telegrator.rb'
    - 'lib/telegrator/cli.rb'
    - 'lib/telegrator/generators.rb'
    - 'lib/telegrator/generators/base.rb'
    - 'lib/telegrator/generators/bot/generator.rb'
